### ISSUE TITLE
Code folding could use some improvements

### ISSUE THREAD

**Issue by atuttle** [circlecell/jsoncompare.com#4]
Since an array of objects doesn't get a linebreak between the `[` and `{`, when you attempt to collapse the entire array only the first object collapses:

![image](https://user-images.githubusercontent.com/46990/27289547-4af6d9e2-54d8-11e7-9f87-2a1451ebff7e.png)

Also, if an array with multiple objects exist with no linebreaks pre-formatting, then they are kept without linebreaks by the formatter (e.g. `}, {`) which results in this:

![image](https://user-images.githubusercontent.com/46990/27289602-7e685c24-54d8-11e7-8b80-dd4873b9d06e.png)

Note that every other object itself is collapsed and the remaining objects can't be collapsed.

If I add a linebreak between `[` and `{` and then collapse the array, it works as expected, hiding all of the array contents.

**Comment by finom** [comment]
@atuttle thank you for the issue. At this project and at other ones we use third-party projects. The issue you reported is about CodeMirror editor and about the behavior its addon. Since we are not the guys who created this addon it's quite hard to fix this minor problem. I'm going to talk to the team but I don't think it is a priority for us.

**Comment by atuttle** [comment]
If your JSON prettify code forced a linebreak between `[` and `{`, and also somewhere in the middle of `},{`, it would work around this issue. :)
